version: '1.1'

services:

  # api:
  #   build: 
  #     context: .
  #     dockerfile: ./apps/api/Dockerfile
  #   ports:
  #     - 3001:3000
  #   volumes:
  #     - ./:/app
  #   depends_on:
  #     - lootify_db
  #   networks:
  #     - lootyfi_network
  lootify_db:
    image: mongo
    ports:
     - 27017:27017
    volumes:
      - ./data:/usr/src/app/data
    networks:
      - lootyfi_network


networks:
  lootyfi_network:
    driver: bridge
    