import Navbar from './components/navbar/layout';
import WalletWrapper from './connections/WalletWrapper';
import './global.css';
import localFont from 'next/font/local';

export const metadata = {
  title: 'Welcome to looty',
  description: 'Generated by create-nx-workspace',
};

const adlamFont = localFont({
  src: [
    {
      path: '../public/fonts/ADLaMDisplay-Regular.ttf',
      weight: '400',
    },
  ],
});


export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className={adlamFont.className}>
      <WalletWrapper>
        <body>
          <Navbar />
          {children}
        </body>
      </WalletWrapper>
    </html>
  );
}
